package com.ggg.home.utils

object Constant {
    const val STATUS_UNCOMPLETED = 0
    const val STATUS_COMPLETED = 1

    const val IS_FOLLOW = 1
    const val IS_UNFOLLOW = 0

    const val IS_NOT_DOWNLOAD = 0
    const val IS_DOWNLOADED = 1
    const val IS_DOWNLOADING = 2

    const val SIGNATURE_IMAGE_CACHE = "HeavenToon"

    const val TYPE_SHOW_COMIC_DETAIL = "SHOW_COMIC_DETAIL"

    const val TOPIC_TYPE_COMMENT = "comment"
    const val TOPIC_TYPE_REPLY = "reply"

    const val RANK_TYPE_ALL = "all"
    const val RANK_TYPE_DAY = "daily"
    const val RANK_TYPE_WEEK = "weekly"
    const val RANK_TYPE_MONTH = "monthly"
    const val RANK_TYPE_YEAR = "yearly"

    const val FILTER_COMIC_STATUS_ALL = "All"
    const val FILTER_COMIC_STATUS_UPDATING = "Updating"
    const val FILTER_COMIC_STATUS_UPDATED = "Updated"

    const val FILTER_COMIC_TYPE_POPULAR = "Popular"
    const val FILTER_COMIC_TYPE_NEW = "New"
    const val FILTER_COMIC_TYPE_UPDATED = "Updated"

    const val ACTION_CLICK_ON_SLIDE = 1
    const val ACTION_CLICK_ON_LIST_CATEGORY = 2
    const val ACTION_CLICK_ON_COMIC = 3
    const val ACTION_CLICK_ON_CHAPTER = 4
    const val ACTION_CLICK_ON_IMAGE_COMIC_TO_SHOW_NAVIGATION = 5
    const val ACTION_CLICK_ON_ITEM_CATEGORY_OF_COMIC_DETAIL = 6
    const val ACTION_CLICK_ON_LIST_REPLIES_COMMENT = 7
    const val ACTION_CLICK_ON_BUTTON_COMMENT_IN_COMIC_DETAIL = 8
    const val ACTION_CLICK_ON_COMIC_HISTORY = 9
    const val ACTION_CLICK_ON_BUTTON_DELETE_COMMENT = 10
    const val ACTION_CLICK_ON_ITEM_MY_COMMENT = 11
    const val ACTION_LOAD_MORE_COMMENT_OF_COMIC_DETAIL = 12
    const val ACTION_CLICK_ON_BUTTON_LOAD_LATEST_CHAPTER = 13
    const val ACTION_CLICK_ON_BUTTON_LOAD_OLDEST_CHAPTER = 14
    const val ACTION_PULL_TO_REFRESH_LIST_COMIC_LATEST_UPDATE = 15
    const val ACTION_LOAD_LIST_COMIC_LATEST_UPDATE = 16
    const val ACTION_LOAD_LIST_COMIC_FILTER = 17
    const val ACTION_CLOSE_STATUS_TYPE_FILTER_SELECT_VIEW = 18
    const val ACTION_CLOSE_CATEGORY_FILTER_SELECT_VIEW = 19
    const val ACTION_CLICK_ON_ITEM_STATUS_TYPE_FILTER = 20
    const val ACTION_CLICK_ON_ITEM_CATEGORY_FILTER = 21
    const val ACTION_CLICK_ON_COMIC_WITH_CATEGORY_MODEL = 22
    const val ACTION_LOAD_LIST_COMIC_BY_FILTER = 23
    const val ACTION_LOAD_MORE_LIST_COMIC_HISTORY = 24
    const val ACTION_CLICK_ON_CHAPTER_TO_DOWNLOAD_IMAGE = 25
    const val ACTION_HIDE_REPORT_COMIC_VIEW = 26
    const val ACTION_SEND_REPORT = 27
    const val ACTION_LOAD_MORE_LIST_COMIC_DOWNLOADED = 28
    const val ACTION_CLICK_ON_COMIC_DOWNLOADED = 29
    const val ACTION_LOAD_MORE_LIST_COMIC_FOLLOW = 30
    const val ACTION_SELECT_OR_DESELECT_COMIC_TO_EDIT = 31
}
